stages:
  stage_01:
    cmd: python satge_01.py
    deps:
      - stage_01.py 
    outs:
      - artifact.txt


  stage_02:
    cmd: python satge_02.py
    deps:
      - artifact.txt
      - stage_02.py
